name: sciencesearch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools>=64
  - setuptools_scm>=7
  - scipy<=1.12
  - beautifulsoup4
  - pandas
  - openpyxl
  - matplotlib
  - scikit-learn
  - lxml
  - jupyter
  - jupyterlab
  - pip:
    - gensim
    - rake_nltk
    - yake
    - spacy
    - nltk
    - git+https://github.com/boudinfl/pke.git
    - -e .